Library/FreeBooks/urls.py
from django.urls import path, re_path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'FreeBooks'

urlpatterns = [
    path('', home_view.as_view(), name='home'),
    path('book/<pk>', book_view.as_view(), name='book_detail'),
    path('books/', book_list_view.as_view(), name='book_list'),
    path('categories/', category_list_view.as_view(), name='category_list'),
    path('authors/', authorsListView.as_view(), name='AuthorList'),
    path('author/<int:pk>', authorsDetailView.as_view(), name='AuthorDetail'),
    path('register/', create_profile, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='FreeBooks/registration/login.html'), name='login'),
    path('profile/', user_profile.as_view(), name='user_profile'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    re_path(r'^search$', Search.as_view(), name='search_result'),
	path('books/<pk>', book_author_list.as_view(), name='book_author_list'),
	path('categoriesBooks/<pk>', category_books_list.as_view(), name='category_books_list'),
    path('wishList/', wish_list_view.as_view(), name='wish_list'),
    path('readList/', read_list_view.as_view(), name='read_list'),
    path('Follow/', follow_list_view.as_view(), name='follow_list'),
    path('Favourite/', favourite_list_view.as_view(), name='favourite_list'),
]

Library/Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('FreeBooks/', include('FreeBooks.urls')),
	path('', RedirectView.as_view(url='/FreeBooks/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library/FreeBooks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Author(models.Model):

    class Meta:
        verbose_name = "Author"
        verbose_name_plural = "Authors"

    author_id = models.AutoField("Author ID", primary_key=True)
    name = models.CharField("Author name", max_length=50)
    pic = models.ImageField("Author Picture", blank=True, upload_to="author_pic")
    bio = models.TextField("Bio", blank=True)
    birth_date = models.DateField("Date of Birth", null=True, blank=True)
    death_date = models.DateField("Date of Death", null=True, blank=True)

    def __str__(self):
        return self.name

class Category(models.Model):

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    category_id = models.AutoField("Category", primary_key=True)
    name = models.CharField("Category Name", max_length=50)
    pic = models.ImageField("Categor Cover", blank=True, upload_to='category_cover')

    def __str__(self):
        return self.name


class Book(models.Model):

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"

    book_id = models.AutoField("Book ID", primary_key=True)
    author = models.ForeignKey(Author, related_name="Write", on_delete=models.CASCADE, verbose_name="Author")
    title = models.CharField("Book Name", max_length=50)
    category = models.ForeignKey(Category, related_name="has_books", on_delete=models.CASCADE, default='')
    publish_date = models.DateField("Published at", null=True, blank=True)
    country = models.CharField("Country", max_length=50, blank=True)
    link = models.URLField("Link", blank=True)
    pic = models.ImageField("Book Cover", blank=True, upload_to='book_cover')
    summary = models.TextField("Summary", blank=True)

    def __str__(self):
        return self.title




class Profile(models.Model):
    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    birth_date = models.DateField("Date of Birth", null=True, blank=True)
    pic = models.ImageField("Profile Picture", blank=True, upload_to='user_profiles')
    bio = models.TextField("Bio", blank=True)
    favourite_category = models.ManyToManyField(Category, through='FavouriteCategory', related_name='favored_by')
    rating = models.ManyToManyField(Book, through='Rate', related_name='rated_by')
    reading = models.ManyToManyField(Book, through='Read', related_name='read_by')
    wish = models.ManyToManyField(Book, through='WishList', related_name='wished_by')
    follows = models.ManyToManyField(Author, through='Follower', related_name='followed_by')

    def __str__(self):
        return self.user.first_name


class Rate(models.Model):

    class Meta:
        verbose_name = "Rate"
        verbose_name_plural = "Rates"
        unique_together = (('user', 'book'),)

    rate_id = models.AutoField("Rate ID", primary_key=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="User")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Book")
    score = models.PositiveSmallIntegerField()

    def __str__(self):
        return str(self.rate_id)



class Read(models.Model):

    class Meta:
        verbose_name = "Read"
        verbose_name_plural = "Reads"
        unique_together = (('user', 'book'),)

    read_id = models.AutoField("Read ID", primary_key=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="User")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Book")

    def __str__(self):
        return str(self.read_id)


class WishList(models.Model):

    class Meta:
        verbose_name = "WishList"
        verbose_name_plural = "WishLists"
        unique_together = (('user', 'book'),)

    wish_id = models.AutoField("Wish ID", primary_key=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="User")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Book")

    def __str__(self):
        return str(self.wish_id)


class Follower(models.Model):

    class Meta:
        verbose_name = "Follower"
        verbose_name_plural = "Followers"
        unique_together = (('user', 'author'),)

    follow_id = models.AutoField("Follow ID", primary_key=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="User")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="Author")

    def __str__(self):
        return str(self.follow_id)


class FavouriteCategory(models.Model):

    class Meta:
        verbose_name = "FavouriteCategory"
        verbose_name_plural = "FavouriteCategories"
        unique_together = (('user', 'category'),)

    favorite_id = models.AutoField("Favorite ID", primary_key=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="User")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Category")

    def __str__(self):
        return str(self.favorite_id)

Library/FreeBooks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, DetailView, ListView
from .models import Book, Category, Author, Profile, Read, Rate, WishList, Follower,FavouriteCategory
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import transaction
from django.contrib import messages
from django.http import HttpResponse
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class home_view(TemplateView):
    def get(self, request):
        return render(request, 'FreeBooks/HomePage.html')


class book_view(DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id
        book = self.kwargs['pk']

        user = Profile.objects.filter(user_id=current_user)
        user = len(user) and user[0]

        read = Read.objects.filter(user_id=current_user, book_id=book)
        read = len(read) and read[0]

        rate = Rate.objects.filter(user_id=current_user, book_id=book)
        rate = len(rate) and rate[0].score
        rate_list = []
        rate_title = ('Poor', 'Fair', 'Good', 'Excellent', 'WOW!!!')
        for i in range(rate):
            rate_list.append(('star selected', rate_title[i], i + 1))
        for j in range(5 - rate):
            rate_list.append(('star', rate_title[j + rate], j + rate + 1))

        wish = WishList.objects.filter(user_id=current_user, book_id=book)
        wish = len(wish) and wish[0]

        context.update({
            'read': read,
            'wish': wish,
            'rate': rate_list,
        })
        return context

    def post(self, request, **kwargs):
        body = json.loads(self.request.body.decode("utf-8"))
        for field in body:
            if field == 'rate':
                Rate.objects.update_or_create(user_id=self.request.user.id, book_id=self.kwargs['pk'], defaults={'score': body[field]})

            elif field =='read' and body[field]:
                Read.objects.get_or_create(user_id=self.request.user.id, book_id=self.kwargs['pk'])
                wishRecord = WishList.objects.filter(user_id=self.request.user.id, book_id=self.kwargs['pk'])
                if wishRecord.exists():
                    wishRecord[0].delete()

            elif field == 'unread' and body[field]:
                readRecord = Read.objects.filter(user_id=self.request.user.id, book_id=self.kwargs['pk'])
                if readRecord.exists():
                    readRecord[0].delete()

            elif field == 'wish' and body[field]:
                WishList.objects.get_or_create(user_id=self.request.user.id, book_id=self.kwargs['pk'])
                readRecord = Read.objects.filter(user_id=self.request.user.id, book_id=self.kwargs['pk'])
                if readRecord.exists():
                    readRecord[0].delete()

            elif field == 'unwish' and body[field]:
                wishRecord = WishList.objects.filter(user_id=self.request.user.id, book_id=self.kwargs['pk'])
                if wishRecord.exists():
                    wishRecord[0].delete()

        return HttpResponse("hello")



class book_list_view(ListView):
    model = Book
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id

        user = Profile.objects.filter(user_id=current_user)
        user = len(user) and user[0]
        if user:
            reads = user.reading.all()
            wishes = user.wish.all()
            rates = user.rating.all()
        for book in context['book_list']:
            book.read = user and book in reads
            book.wish = user and book in wishes
            rate = user and Rate.objects.filter(user_id=current_user, book_id=book)
            rate = bool(rate) and len(rate) and rate[0].score
            book.rate = []
            rate_title = ('Poor', 'Fair', 'Good', 'Excellent', 'WOW!!!')
            for i in range(rate):
                book.rate.append(('star selected', rate_title[i], i + 1))
            for j in range(5 - rate):
                book.rate.append(('star', rate_title[j + rate], j + rate + 1))
        return context

class category_list_view(ListView):
    model = Category
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id

        user = Profile.objects.filter(user_id=current_user)
        user = len(user) and user[0]
        if user:
            categories = user.favourite_category.all()
        else:
            categories = Category.objects.all()
        for category in context['category_list']:
            category.favourite = user and category in categories
        return context


class authorsListView(ListView):
    model=Author
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id

        user = Profile.objects.filter(user_id=current_user)
        user = len(user) and user[0]
        if user:
            authors = user.follows.all()
        else:
            authors = Author.objects.all()
        for author in context['author_list']:
            author.followed = user and author in authors
        return context

class authorsDetailView(DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id
        author = self.kwargs['pk']

        user = Profile.objects.filter(user_id=current_user)
        user = len(user) and user[0]

        follows = Follower.objects.filter(user_id=current_user, author_id=author)
        follows = len(follows) and follows[0]

        context.update({
            'follow': follows
        })
        return context
    def post(self, request, **kwargs):
        body = json.loads(self.request.body.decode("utf-8"))
        print(body)
        for field in body:
            if field =='follow' and body[field]:
                Follower.objects.get_or_create(user_id=self.request.user.id, author_id=self.kwargs['pk'])
            elif field == 'unfollow' and body[field]:
                followRecord = Follower.objects.filter(user_id=self.request.user.id, author_id=self.kwargs['pk'])
                if followRecord.exists():
                    followRecord[0].delete()
        return HttpResponse("here")
class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('birth_date', 'bio', 'pic')

@transaction.atomic
def create_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user_id = user.id
            profile.save()
            messages.success(request, ('You have registered successfully!'))
            return redirect('FreeBooks:login')
        else:
            email = request.POST['email']
            username = request.POST['username']
            isEmail = bool(User.objects.filter(email=email))
            print(user_form.errors)
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'FreeBooks/registration/register.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

class Search(ListView):

    class Meta:
        verbose_name = "Search"
        verbose_name_plural = "Searches"

    template_name = 'FreeBooks/search.html'
    context_object_name = 'character_series_list'
    model = Book

    def get_context_data(self, **kwargs):
        q = self.request.GET.get('q', '')
        page1q = self.request.GET.get('page1', '')
        page2q = self.request.GET.get('page2', '')
        querystring = {'q': q, 'page1': page1q, 'page2':page2q}
        context = super().get_context_data(**kwargs)
        book_list = Book.objects.filter(title__icontains=q)
        paginator = Paginator(book_list, 2)
        page1 = self.request.GET.get('page1')
        try:
            book_list = paginator.page(page1)
        except PageNotAnInteger:
            book_list = paginator.page(1)
        except EmptyPage:
            book_list = paginator.page(paginator.num_pages)

        author_list = Author.objects.filter(name__icontains=q)
        paginator = Paginator(author_list, 2)
        page2 = self.request.GET.get('page2')
        try:
            author_list = paginator.page(page2)
        except PageNotAnInteger:
            author_list = paginator.page(1)
        except EmptyPage:
            author_list = paginator.page(paginator.num_pages)


        current_user = self.request.user.id
        user = Profile.objects.filter(user_id=current_user)
        user = len(user) and user[0]
        if user:
            reads = user.reading.all()
            wishes = user.wish.all()
            rates = user.rating.all()
        for book in book_list:
            book.read = user and book in reads
            book.wish = user and book in wishes
            rate = user and Rate.objects.filter(user_id=current_user, book_id=book)
            rate = bool(rate) and len(rate) and rate[0].score
            book.rate = []
            rate_title = ('Poor', 'Fair', 'Good', 'Excellent', 'WOW!!!')
            for i in range(rate):

Library/FreeBooks/templates/FreeBooks/HomePage.html
{% extends "FreeBooks/base.html" %}
{% load static %}

{% block bar_home %}
    <li class="active"><a href="{% url 'FreeBooks:home' %}">Home</a></li>
{% endblock bar_home %}

{% block siteContent %}
    <h1>Online Library </h1>
    <p>The library has the following record counts:</p>
{% endblock %}

Library/FreeBooks/templates/FreeBooks/author_detail.html
{% extends "FreeBooks/base.html" %}
{% load static %}

{% block siteTitle %}
    {{ author.name|title }}
{% endblock siteTitle %}


{% block cssFiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'FreeBooks/css/author_detail.css' %}" />
{% endblock cssFiles %}


{% block bar_authors %}
    <li class="active"><a href="{% url 'FreeBooks:AuthorList' %}">Authors</a></li>
{% endblock bar_authors %}


{% block siteContent %}
    {% csrf_token %}
    <div class="imageColumn">
        <div class="authorProfile">
            <a href="{{ author.pic.url }}"><img id="authorPic" alt="{{ author.name|title }}" src="{{ author.pic.url }}"></a>
        </div>
        <div class="buttons">
            {% if follow %}
                <button id="unfollow" class="funcBtn active_btn">Unfollow</button>
            {% else %}
                <button id="follow" class="funcBtn inactive_btn">+ Follow</button>
            {% endif %}
        </div>
    </div>

    <div class="metacol">
        <div id="data" class="stacked">
            <h1 id="authorName" class="bookeName" itemprop="name">
                {{ author.name|title }}
            </h1>
            <span class="by smallText">Born: </span>
            <span class="by smallText">{{ author.birth_date }}</span>
            {% if author.death_date %}
                <span class="by smallText">, Died: </span>
                <span class="by smallText">{{ author.death_date }}</span>
            {% endif %}
            <span class="by smallText">, <a href="{% url 'FreeBooks:book_author_list' author.author_id %}">Books</a></span>
        </div>
        <div id="biography" class="readable stacked" style="right:0">
            <span id="freeTextContainer5022597030680236223">
                {{ author.bio|truncatewords:30 }}
            </span>
            <span id="freeText5022597030680236223" style="display:none">
                {{ author.bio }}
            </span>
            <a data-id="5022597030680236223" href="#" onclick="swapContent($(this));; return false;">more</a>
        </div>
    </div>
{% endblock %}

{% block jsFiles %}
    <script type="text/javascript" src="{% static 'FreeBooks/js/author_detail.js' %}"></script>
{% endblock jsFiles %}

Library/FreeBooks/templates/FreeBooks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
    {% block siteTitle %}

    {% endblock siteTitle %}
    </title>
    <meta charset="utf-8">
    <meta name="FreeBook">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'FreeBooks/css/base.css' %}" />
    {% block cssFiles %}

    {% endblock cssFiles %}

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-style: oblique; font-weight: bold;" href="">FreeBooks</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    {% block bar_home %}
                        <li><a href="{% url 'FreeBooks:home' %}">Home</a></li>
                    {% endblock bar_home %}
                    {% comment %}
                        {% block bar_about %}
                            <li><a href="#">About</a></li>
                        {% endblock bar_about %}
                    {% endcomment %}
                    {% block bar_categories %}
                        <li><a href="{% url 'FreeBooks:category_list' %}">Categories</a></li>
                    {% endblock bar_categories %}
                    {% block bar_authors %}
                        <li ><a href="{% url 'FreeBooks:AuthorList' %}">Authors</a></li>
                    {% endblock bar_authors %}
                    {% block bar_books %}
                        <li><a href="{% url 'FreeBooks:book_list' %}">Books</a></li>
                    {% endblock bar_books %}
                    {% block bar_profile %}
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'FreeBooks:user_profile' %}">Profile</a></li>
                        {% endif %}
                    {% endblock bar_profile %}
                </ul>
                <ul class="nav navbar-nav navbar-right">                    
                    {% if user.is_authenticated %}
                        <li id="logoutIcon"><a href="{% url 'FreeBooks:user_profile' %}"><span class="glyphicon glyphicon-user"></span>  {{ user.first_name|title }}</a></li>
                        <li id="logoutIcon"><a href="{% url 'FreeBooks:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Log Out</a></li>
                    {% else %}
                        <li id="loginIcon"><a href="{% url 'FreeBooks:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        <li id="registerIcon"><a href="{% url 'FreeBooks:register' %}"><span class="glyphicon glyphicon-sign-up"></span>Signup</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form" role="search" action="{% url 'FreeBooks:home' %}search" method="get" id="srchForm">
                        <div class="input-group add-on">
                            <input class="form-control" placeholder="Search..." name="q" id="srch-term" type="text">
                            <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid text-center">
        <div class="row content">
            <div class="col-sm-2 sidenav">
                <p><a href=" "></a></p>
                <p><a href=" "></a></p>
                <p><a href=" "></a></p>
            </div>
            <div class="col-sm-8 text-left">
                {% block siteContent %}

                {% endblock siteContent %}
            </div>
                <div class="bio">
                    {% block bioContent %}

                    {% endblock bioContent %}
                </div>
            <div class="col-sm-2 sidenav">

            </div>
        </div>
    </div>
    <footer class="container-fluid text-center">
        <p></p>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block jsFiles %}

    {% endblock jsFiles %}
</body>

</html>

Library/FreeBooks/templates/FreeBooks/book_detail.html
{% extends "FreeBooks/base.html" %}
{% load static %}

{% block siteTitle %}
    {{ book.title |title}} - {{ book.author.name|title }}
{% endblock siteTitle %}


{% block cssFiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'FreeBooks/css/book_detail.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock cssFiles %}


{% block bar_books %}
    <li class="active"><a href="{% url 'FreeBooks:book_list' %}">Books</a></li>
{% endblock bar_books %}


{% block siteContent %}
    {% csrf_token %}
    <div class="imageColumn">
        <div class="bookCover">
            <a href="{{ book.pic.url }}"><img id="coverImage" alt="{{ book.title|title }}" src="{{ book.pic.url }}"></a>
        </div>
        <div class="buttons">
          {% if read %}
            <button id="unread" class="funcBtn active_btn">Done ✔</button>
            </div>
            <div class="buttons">
              <button id="wish" style="display: none;" class="funcBtn inactive_btn">Wish to Read</button>
            </div>
          {% else %}
            <button id="read" class="funcBtn inactive_btn">Read</button>
          </div>
          <div class="buttons">
            {% if wish %}
              <button id="unwish" class="funcBtn active_btn">Will Read! ✔</button>
            {% else %}
                <button id="wish" class="funcBtn inactive_btn">Wish to Read</button>
            {% endif %}
          </div>
          {% endif %}
        <!-- Rating Stars Box -->
        <div class='rating-stars text-center'>
            <ul id='stars'>
              {% for class, titl, value in rate %}
                <li class="{{ class }}" title="{{ titl }}" data-value="{{ value }}">
                    <i class='fa fa-star fa-fw'></i>
                </li>
              {% endfor %}
            </ul>
        </div>
    </div>
    
    <div class="metacol">
      <div id="bookAuthors" class="stacked">
          <h1 id="bookTitle" class="bookTitle" itemprop="name">
                {{ book.title|title }}
          </h1>
          <span class="by smallText">by</span>
          <span>
          <a class="authorName" href="{% url 'FreeBooks:AuthorDetail' book.author.author_id %}">{{ book.author }}</a>
          </span>
          <span class="by smallText"> , {{ book.publish_date }}</span>
          <span class="by smallText"> , <a href="{% url 'FreeBooks:category_books_list' book.category.category_id %}">{{ book.category }}</a></span>
          <span class="by smallText"> , {{ book.country }}</span>
      </div>
      <div id="description" class="readable stacked" style="right:0">
          <span id="freeTextContainer5022597030680236223">
          {{ book.summary|truncatewords:30 }}
          </span>
          <span id="freeText5022597030680236223" style="display:none">
          {{ book.summary }}
          </span>
          <a data-id="5022597030680236223" href="#" onclick="swapContent($(this));; return false;">more</a>
      </div>
    </div>
{% endblock %}

{% block jsFiles %}
    <script type="text/javascript" src="{% static 'FreeBooks/js/book_detail.js' %}"></script>
{% endblock jsFiles %}

Library/FreeBooks/templates/FreeBooks/user.html
{% extends "FreeBooks/base.html" %}
{% load static %}

{% block siteTitle %}
    {{ user.first_name|title }} {{ user.last_name|title }}
{% endblock siteTitle %}


{% block cssFiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'FreeBooks/css/user.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock cssFiles %}


{% block bar_profile %}
    <li class="active"><a href="{% url 'FreeBooks:user_profile' %}">Profile</a></li>
{% endblock bar_profile %}


{% block siteContent %}
    <div class="imageColumn">
        <div class="ProfilePicture">        
            <a href="{{ profile.pic.url }}"><img id="profilePic" alt="{{ profile.title }}" src="{{ profile.pic.url }}"></a>
        </div>
    </div>
    
    <div class="metacol">
        <div id="userData" class="stacked">
            <h1 id="userName" itemprop="name">
            {{ user.first_name|title }} {{ user.last_name|title }}
            </h1>
            <span class="by smallText">{{ profile.birth_date }}</span>
            {% for category in favourite_categories|slice:":3" %}
                <span class="by smallText"> , <a href="{% url 'FreeBooks:category_books_list' category.category_id %}">{{ category }}</a></span>
            {% endfor %}
            <b>
            <span class="by smallText">, <a href="{% url 'FreeBooks:wish_list' %}">Wish List</a></span>
            <span class="by smallText">, <a href="{% url 'FreeBooks:read_list' %}">Read List</a></span>
            <span class="by smallText">, <a href="{% url 'FreeBooks:follow_list' %}">Authors</a></span>
            <span class="by smallText">, <a href="{% url 'FreeBooks:favourite_list' %}">Categories</a></span></b>
        </div>
      <div id="userBio" class="readable stacked" style="right:0">
          <span id="freeTextContainer5022597030680236223">
          {{ profile.bio|truncatewords:30 }}
          </span>
          <span id="freeText5022597030680236223" style="display:none">
          {{ profile.bio }}
          </span>
          <a data-id="5022597030680236223" href="#" onclick="swapContent($(this));; return false;">more</a>
      </div>
    </div>
{% endblock %}

{% block jsFiles %}
    <script type="text/javascript" src="{% static 'FreeBooks/js/user.js' %}"></script>
{% endblock jsFiles %}